#!/bin/bash
set -e

echo "============================================="
echo " CONFIGURACIÓN DE SECURITY GROUPS EN AWS"
echo "============================================="
echo "Crea el grupo de seguridad 'sg-proyecto-sre' en la VPC de la instancia EC2."
echo "Reglas entrantes (Ingress):"
echo ""
echo "+----------------+--------+---------------------+-----------------------------------"
echo "| Tipo           | Puerto | Origen              | Justificación                     "
echo "+----------------+--------+---------------------+-----------------------------------"
echo "| SSH            | 22     | 0.0.0.0/0 (restringir a tu IP) | Admin remoto            "
echo "| HTTP           | 80     | 0.0.0.0/0           | Redirección a HTTPS (Nginx)      "
echo "| HTTPS          | 443    | 0.0.0.0/0           | API con Let's Encrypt            "
echo "| Custom TCP     | 5000   | 0.0.0.0/0           | API Flask (acceso directo)       "
echo "| Custom TCP     | 3001   | 0.0.0.0/0           | Uptime Kuma                      "
echo "| Custom TCP     | 8080   | 0.0.0.0/0           | Dozzle logs                      "
echo "| Custom TCP     | 3306   | 0.0.0.0/0 (solo si realmente se expone) | MySQL (NO recomendado) "
echo "| Custom TCP     | 81     | 0.0.0.0/0           | Panel admin Nginx Proxy Manager  "
echo "+----------------+--------+---------------------+-----------------------------------"
echo ""
echo "RECOMENDACIÓN DE SEGURIDAD:"
echo "  - Limitar puertos de admmistración (22, 81) a tu IP pública en vez de 0.0.0.0/0."
echo "  - NO exponer el puerto 3306 públicamente; MySQL solo debe ser alcanzable"
echo "    dentro de la red interna de Docker (red-internal)."
